Comentarios y correccion de digitos cedula
cfjohnny/Grupo02_ProgramacionBasicaIC2023 pull request #6
Opened 2023-04-07 01:01 UTC by Bmow1402

Agregue los comentarios que explican cada codigo y sus funciones y finalmente, trate de arreglar este punto en el codigo:
i. Si los dígitos de la cédula son mayores a 9, imprimir un mensaje que le alerte al usuario que no puede digitar más de 9 dígitos.
ii. Si los dígitos de la cédula son menores a 9, imprimir un mensaje que le alerte al usuario que no puede digitar menos de 9 dígitos.

2023-04-17 02:23 UTC, MelZinke commented on DepositoObligatorioParaRegistrarUsuario.py
> +            except (ValueError, IndexError): #En caso de obtener un error, para hacerlo facil de entender al usuario, se le educara imprimiendo un mensaje.
Excelente 👍

2023-04-17 02:44 UTC, MelZinke approved these changes

2023-04-17 02:44 UTC, MelZinke commented on trishel.py
> +        print("Seleccione una opción valida")
Los cambios de esto hay que hacerlos en el archivo `Proyecto_Cajero.py`

2023-04-17 02:44 UTC, MelZinke commented on DepositoObligatorioParaRegistrarUsuario.py
> +        montoMinimo = 100000 / tasaDeCambio[moneda]
Hay un archivo de constantes donde podemos usar esos valores como el 100000.
Puedes poner en `constantes.py` la variable `montoMinimo = 100000`.
Y despues en este codigo hacer el import al inicio de este archivo: `import constantes as const`. 
Y al final en esta linea poner: `montoMinimo = const.montoMinimo / tasaDeCambio`

2023-04-17 02:47 UTC, MelZinke approved these changes

2023-04-17 03:52 UTC, MelZinke requested changes

2023-04-17 03:52 UTC, MelZinke commented on trishel.py
> +        print("Seleccione una opción valida")
Los cambios de esto hay que hacerlos en el archivo `Proyecto_Cajero.py`

2023-04-19 00:06 UTC, nazavn approved these changes

2023-04-25 03:35 UTC, closed without merging